# Generated by Django 5.2.2 on 2025-06-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('items', models.TextField()),
            ],
        ),
    ]
